name: SurvivalTools
version: ${project.version}
author: Vexatone

main: com.vexatone.survivaltools.survivaltools.SurvivalTools
api-version: 1.16
commands:
  pl:
    description: Plugin-related commands.
    usage: /pl <action>